version: "3"

services:
  shazarr-api:
    build: "./docker"
    container_name: "shazarr-api"
    ports:
      - 12358:12358
    volumes:
      - .:/home/app/standalone
    environment:
      - LIDARR_API_KEY=
      - LIDARR_URL=
      - LIDARR_LIBRARY_PATH=
      - TIDARR_URL=
